Feature - Adoption register screen
animavita/animavita pull request #111
Opened 2021-10-27 18:04 UTC by petruspierre

closes #76 

Description:
Created a custom hook to handle the adoption register using context API and react hook form

DEMO:

https://user-images.githubusercontent.com/39802870/139121584-4ed0f9aa-e2d0-4e38-9894-ab59b6a35504.mp4

2021-11-04 15:15 UTC, belgamo requested changes
Thank you for helping us a lot with excellent PR!

2021-11-04 15:15 UTC, belgamo commented on packages/expo/src/modules/adoption/AdoptionForm.tsx
> +  const getInputElement = (data: InputData) => {
I think you can place this outside of the component.

2021-11-04 15:15 UTC, belgamo commented on packages/expo/src/modules/adoption/AdoptionForm.tsx
> +    } else {
How about adding an earlier return? Like:

```js
if(!error) return;

const error = errors[name];

return (
   <Typography css={[`margin-bottom: ${px2ddp(4)}px;`]} variant="caption-1">
      {t('required_field')}
   </Typography>
);
```

2021-11-04 15:15 UTC, belgamo commented on packages/expo/src/modules/adoption/Controller.tsx
> +  const [data, setData] = useState<Partial<Fields>>({});
In order to make it easier to understand, I suggest transforming the data state into a `useReducer`. You have two small reducers for step and another one for images. Also, I think you don't need a data state to store form info. So I think would be great to unify all reducers and the data state. What do you think?

2021-11-04 15:15 UTC, belgamo commented on packages/expo/src/modules/adoption/__tests__/AdoptionForm.test.tsx
> +import {Mount} from '../../../../tests/helpers';
Use absolute import here, please.

2021-11-04 15:15 UTC, belgamo commented on packages/expo/src/modules/adoption/reducers.ts
> +import * as ImagePicker from 'expo-image-picker';
Missing unit tests for reducers. See my comment above about unifying all reducers in just a single one.

2021-11-04 15:15 UTC, belgamo commented on packages/ui/assets/images/PhotoContainerImage.tsx
> +  // @ts-ignore
Why do we need this here?

2021-11-04 15:15 UTC, belgamo commented on packages/ui/core/Button/__tests__/ButtonGroup.test.tsx
> +describe('Header component', () => {
I think you mean "ButtonGroup component"?

2021-11-08 13:38 UTC, petruspierre commented on packages/ui/assets/images/PhotoContainerImage.tsx
> +  // @ts-ignore
forgot to remove it xD, thanks

2022-10-31 00:37 UTC, closed without merging