Create user and auth module
animavita/animavita pull request #135
Opened 2022-11-13 03:23 UTC by JVBorges

2023-01-02 11:49 UTC, belgamo requested changes
Thanks for contributing. There are a few things we need to tweak but overall looks good!

2023-01-02 11:49 UTC, belgamo commented on apps/backend/src/user/entities/mongodb/user.schema.ts
> +    photoUri: String,
Should be optional

2023-01-02 11:49 UTC, belgamo commented on apps/backend/src/auth/auth.service.spec.ts
> +  });
Not a big deal, that's fairly well. However, I am a big fan of taking a more functional approach and creating a setup function and get rid of your `beforeEach`, something similar to this:

Outside of describe:

```js
const setup = () => {
 const module = await Test.createTestingModule({ ... })

 service = module.get<AuthService>(AuthService);
 jwtService = module.get<JwtService>(JwtService);

 return {
  service,
  jwtService,
 }
}
```

Then, on each test:
```js
it('should be defined', () => {
 const { service } = setup();

 expect(service).toBeDefined();
});
```

This way you ensure you have a totally new variable (any other test did not use that). I know your `beforeEach` is performing this job but I really think that using the `setup` approach makes your test more explicit for other developers.

WDYT?

2023-01-02 11:49 UTC, belgamo commented on apps/backend/src/auth/auth.service.spec.ts
> +      await new Promise((r) => setTimeout(r, 1000));
Try to mock the module responsible for making you await as we talked about on discord.

2023-01-02 11:49 UTC, belgamo commented on apps/backend/src/auth/auth.service.spec.ts
> +      await new Promise((r) => setTimeout(r, 1000));
Same as above.

2023-01-02 11:49 UTC, belgamo commented on apps/backend/src/user/user.service.ts
> +  findById(userId: string) {
Don't we need to implement a conditional for the case where the user is not found and then throw an error, as you did for `findById`?

2023-01-02 11:49 UTC, belgamo commented on apps/backend/test/e2e/auth.e2e-spec.ts
> +    await new Promise((r) => setTimeout(r, 1000));
Same as the other timeouts you have

2023-01-02 11:49 UTC, belgamo commented on shared/models/user.ts
> +  photoUri: string;
Let's make it optional since we don't want to require users to upload a picture while signing up.

2023-01-02 11:49 UTC, belgamo commented on shared/validation-schemas/src/auth.ts
> +  );
EOF

2023-01-02 11:49 UTC, belgamo commented on apps/backend/test/e2e/auth.e2e-spec.ts
> +  });
Take a look at my comment about `setup` approach.

2023-01-02 11:49 UTC, belgamo commented on apps/backend/src/user/user.service.ts
> +    return this.userRepository.findByEmail(email);
Same as above

2023-01-02 11:49 UTC, belgamo commented on apps/backend/src/user/user.service.spec.ts
> +  });
Take a look at my comment about `setup` approach.

2023-02-06 23:24 UTC, JVBorges commented on apps/backend/src/user/user.service.ts
> +  findById(userId: string) {
With these simple queries function, I prefer to leave the validation responsibility to the calling function. I found it easier than using a try-catch.

2023-02-09 15:07 UTC, belgamo commented on apps/backend/src/auth/auth.service.spec.ts
> +      expect(spiedFunction).toBeCalled();
`toBeCalledTimes` to make sure it was called only once.

2023-02-09 15:07 UTC, belgamo commented on apps/backend/src/user/user.service.spec.ts
> +    it('should find a user by his id', async () => {
```suggestion
    it('should find a user by their id', async () => {
```

2023-02-09 15:07 UTC, belgamo commented on apps/backend/src/user/user.service.spec.ts
> +    it('should find a user by his email', async () => {
```suggestion
    it('should find a user by their email', async () => {
```

2023-02-09 15:07 UTC, belgamo commented on apps/backend/src/auth/auth.service.spec.ts
> +    update: jest.fn().mockResolvedValue(persistedUser),
Do you really need `jest.fn()` here? What about just `create: Promise.resolve(persistedUser)`

2023-02-09 15:07 UTC, belgamo commented on apps/backend/src/auth/auth.service.ts
> +          expiresIn: '1h',
Could you use a constant for that?

2023-02-09 15:07 UTC, belgamo commented on apps/backend/src/auth/auth.service.ts
> +          expiresIn: '7d',
Same as above

2023-02-09 15:07 UTC, belgamo commented on apps/backend/src/user/repositories/mongodb/user.schema.ts
> +    },
What about [geospatial-queries](https://www.mongodb.com/docs/manual/geospatial-queries/)?

2023-02-09 15:07 UTC, belgamo commented on apps/backend/test/e2e/auth.e2e-spec.ts
> +  });
Not a big deal but you nest describe blocks to make the expected output explicit:

```js
describe('/POST auth/signUp', () => {
 it('returns a successful message', () => { ... })
})
```

2023-02-09 23:46 UTC, JVBorges commented on apps/backend/src/auth/auth.service.spec.ts
> +    update: jest.fn().mockResolvedValue(persistedUser),
Not really I think, but why preferring this way instead?

2023-02-10 11:17 UTC, belgamo commented on apps/backend/src/auth/auth.service.spec.ts
> +    update: jest.fn().mockResolvedValue(persistedUser),
Just because it's simpler hehe

2023-02-10 11:38 UTC, belgamo approved these changes, later dismissed
Please rebase your branch with `v2`

2023-02-10 11:38 UTC, belgamo commented on apps/backend/.env.example
> +JWT_REFRESH_TOKEN_EXPIRATION=14d
EOF

2023-02-12 22:56 UTC, belgamo submitted a review, later dismissed

2023-02-14 13:28 UTC, belgamo submitted a review, later dismissed

2023-02-15 12:51 UTC, belgamo approved these changes

2023-02-15 12:52 UTC, belgamo commented
Thanks a lot @JVBorges, we did a big progress with this PR 👊

2023-02-15 12:52 UTC, merged