#148: Add pet photos step
animavita/animavita pull request #164
Opened 2023-02-26 23:59 UTC by joaoGabriel55

![image](https://user-images.githubusercontent.com/23138717/221445261-c05e92fd-094e-477f-a7c8-3a15e07ba073.png)
![image](https://user-images.githubusercontent.com/23138717/221445394-5f838417-90ab-4fde-9ccb-14a718d4730f.png)

2023-03-07 00:18 UTC, belgamo requested changes
Awesome PR! Thank you again for the great contributions you've done 👊

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.tsx
> +
`const [firstImage, secondImage, thirdImage] = images;`

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/adoption-form.component.test.tsx
> +  await screen.findByText(/observações/i);
Could you make the observations step the last one?

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/adoption-form.constants.ts
> +    order: 7,
Please make it the last but one

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.test.tsx
> +const usePetPhotosPickerMock = (pickImage = jest.fn()) => {
```suggestion
const mockUsePetPhotos = (pickImage = jest.fn()) => {
```

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.test.tsx
> +  });
How about:

```js
// place this at the top of the file
const IMAGE_SLOTS_IDENTIFIERS = ['first', 'second', 'third'];

describe.each(IMAGE_SLOTS_IDENTIFIERS)('when %s slot is pressed', (slot) => {
 const index = IMAGE_SLOTS_IDENTIFIERS.findIndex((item) => item === slot);

 it(`calls pickImage with ${index}`, () => {
  usePetPhotosPickerMock(pickImage);

  renderWithProviders(<PetUploadPhotosStep />);

  fireEvent.press(screen.getAllByHintText(`uploads the ${slot} pet picture`)[0]);
 });
});
```
By doing that, you can eliminate the `testId` and follow [testing library philosophy](https://testing-library.com/docs/dom-testing-library/api-accessibility/#testing-for-accessibility). See my comment below about accessibility properties.

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.test.tsx
> +  it.skip('displays camera roll permission alert when permission is not granted', async () => {
Why are you skipping that?

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.test.tsx
> +  it.skip('displays media permission granted message when permission is granted', async () => {
Why are you skipping that?

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.tsx
> +  const size = small ? 100 : 220;
100 and 220 could be capitalized constants at the top of the file.

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.hooks.test.ts
> +    await waitFor(() => expect(result.current.images).toEqual([undefined, 'image1', undefined]));
You can also use the jest `each` method to test the three array positions.

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.tsx
> +        <PhotoPicker imageUri={images[0]} onPress={pickImage(0)} alt="Photo 1" testID="Photo 1" />
```suggestion
        <PhotoPicker imageUri={images[0]} onPress={pickImage(0)} alt="Photo 1" accessibilityHint="uploads the first pet picture" />
```

Please add this text to the locale file

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.tsx
> +            testID="Photo 2"
```suggestion
            accessibilityHint="uploads the second pet picture"
```

Please add this text to the locale file

2023-03-07 00:18 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.tsx
> +            testID="Photo 3"
```suggestion
            accessibilityHint="uploads the third pet picture"
```
Please add this text to the locale file

2023-03-07 11:49 UTC, joaoGabriel55 commented on apps/mobile/src/components/register-adoption-form/adoption-form.component.test.tsx
> +  await screen.findByText(/observações/i);
Yeah!

2023-03-08 22:11 UTC, belgamo requested changes

2023-03-08 22:11 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.tsx
> +  if (status !== 'granted') alert(i18next.t('PERMISSIONS.CAMERA'));
Hey let's bother the user with this alert because if the user doesn't grant permission and keeps going back and forth on photos steps, we don't wanna show this alert every time. How about we show a message explaining why we need access to the camera roll and a "Grant permission" button? At this moment you don't need to render the three photo slots, we will only show this when the user grants permission.

2023-03-08 22:11 UTC, belgamo commented on apps/mobile/src/i18n/locales/pt-BR.json
> +    "CAMERA": "Animavita precisa do acesso a câmera"
Please take a look at my comment above about getting rid of alerts. Then, here, let's come up with a friendly message like "Hey, in order to have better chances of finding a new owner for your pet, we need access to your gallery so you can upload some nice pictures".

2023-03-08 22:11 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.tsx
> +
Would be nice to destructure the image array. This way we leave it clear to the other developers that there are three images in the game.

2023-03-08 22:11 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.tsx
> +const SIZES = { SMALL: 100, LARGE: 220 };
```suggestion
const IMAGE_SIZES = { SMALL: 100, LARGE: 220 };
```

2023-03-08 22:11 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.hooks.test.ts
> +  it.each(SLOTS)('pickImage updates the images state', async (slot) => {
Jest output doesn't look clear 

<img width="513" alt="Screen Shot 2023-03-08 at 18 55 52" src="https://user-images.githubusercontent.com/19699724/223859578-56162b62-8b0b-4ef2-8da9-24f0147b463b.png">

Could you concatenate an index just so we can differentiate each one?

2023-03-08 22:35 UTC, belgamo commented on apps/mobile/src/i18n/locales/pt-BR.json
> +    "CAMERA": "Animavita precisa do acesso a câmera"
Actually, you can just remove this.

2023-03-08 22:37 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/compose/form-steps/pet-upload-photos-step/pet-upload-photos-step.component.tsx
> +  if (status !== 'granted') alert(i18next.t('PERMISSIONS.CAMERA'));
Actually, according to the [docs](https://docs.expo.dev/versions/latest/sdk/imagepicker/#usage) you don't need to request the user's consent to access the phone gallery. Let's just remove this whole permission check.

2023-03-13 20:05 UTC, belgamo approved these changes
Excellent! Thank you <3

2023-03-13 20:05 UTC, belgamo commented
I created two new issues to continue the work started here

https://github.com/animavita/animavita/issues/166
https://github.com/animavita/animavita/issues/167

2023-03-13 20:05 UTC, merged