Enhance Codebase with Dynamic Imports and Babel Aliases
animavita/animavita pull request #212
Opened 2023-10-31 16:23 UTC by purevsurena

This pull request introduces improvements to the React Native app by configuring Babel aliases for enhanced module resolution. In three isolated commits, the codebase has been refactored to replace static imports with dynamic ones, providing greater flexibility and maintainability.

Tasks:

- [x] Configure Babel Alias for Improved Module Resolution:
- [x] Replaced static imports with dynamic ones in the App.tsx
- [x] Replaced static imports with dynamic ones in the main-navigator.tsx

Screenshot:
![Screenshot 2023-11-01 at 00 17 37](https://github.com/animavita/animavita/assets/35187128/a7ec8f04-4390-465a-b6d3-0744063a920f)

I recommend granting permission to proceed with the secure replacement of all static imports in the codebase. This action is poised to optimize the application's code structure, fostering a more resilient foundation for future development. If agreeable, I am prepared to take on this task.

2023-11-01 03:24 UTC, purevsurena commented
Hello @belgamo , Please review the above PR.

2023-11-08 01:26 UTC, belgamo commented
Thanks for the contribution! Please, you can use this PR and go ahead to do the replacements for the other files.

2023-11-08 01:27 UTC, belgamo approved these changes, later dismissed

2023-11-08 09:54 UTC, purevsurena commented
> Thanks for the contribution! Please, you can use this PR and go ahead to do the replacements for the other files.

Thank you for your comment. I've replaced all remaining code and conducted a local check, including the full flow. You can now proceed to merge it.

By the way, please ensure to clear the cache and start Metro for the first time.

2023-11-13 11:47 UTC, belgamo requested changes
A few more changes before merging 😄

2023-11-13 11:47 UTC, belgamo commented on apps/mobile/src/components/register-adoption-form/adoption-form.component.tsx
> -import { useMultiStepNavigation } from './hooks/use-multi-step-navigation.hook';
All these four imports are actually part of the `register-adoption-form` component. They aren't meant to be used outside of their host component, that's the purpose of the `compose` folder. WDYT about keeping the dot notation import in this case?

2023-11-13 11:47 UTC, belgamo commented on apps/mobile/src/components/tabs/tabs.component.tsx
> -import CustomTabBar from './compose/tab-bar.component';
Same

2023-11-13 11:47 UTC, belgamo commented on apps/mobile/src/screens/get-location/get-location.screen.tsx
> +import { Warnings } from '@/hooks/use-user-location/use-user-location';
Can you reexport `Warnings` from the index file so we can import both modules at the same line?

2023-11-30 05:09 UTC, purevsurena commented
Hey @belgamo ,

I've addressed the import issue related to the compose folder as suggested. The warning has been resolved and the import now fits into a single line.

I believe the changes are ready for merging. Feel free to review.

2023-11-30 15:05 UTC, belgamo approved these changes

2023-11-30 15:05 UTC, merged